### ISSUE TITLE
퀴즈 관련 schema 제안

### ISSUE THREAD

**Issue by MCprotein** [elice-promotion-site-team/elice-promotion-site-backend#12]
개개인의 맞은 문제 개수는 user-schema 속성에 isSovled, corrected 와 같은 속성을 추가하여 각각 true/false, 개수 값을 저장하여 문제를 풀고난 후 true인 계정들의 맞은 개수를 랭킹으로 보여주면 좋을거같습니다.

퀴즈 문제 각각에 대한 정답률은 quiz-schema를 작성하여 문제번호, 맞은 사람 인원수, 푼 사람 인원수를 저장하여 표기할 수 있을거같습니다.

**Comment by 89yunik** [comment]
동의합니다. 현재 작성 중인 user schema에 해당 내용 추가하겠습니다.

**Comment by MCprotein** [comment]
감사합니다
