### ISSUE TITLE
model에서 반환값 null 인 경우까지 계산하여 발생하는 에러 해결 방안

### ISSUE THREAD

**Issue by MCprotein** [elice-promotion-site-team/elice-promotion-site-backend#13]
![스크린샷 2022-06-22 오후 3 49 05](https://user-images.githubusercontent.com/89785501/174962457-3bfa276d-ddba-4ce1-88f1-f3ee7308f7c7.png)

![스크린샷 2022-06-22 오후 3 46 06](https://user-images.githubusercontent.com/89785501/174961980-f44dc8aa-7c36-4414-9dbb-a0f1505536be.png)

이 에러는 익님이 말씀하신 대로 find 관련 mongoose 메소드를 사용했을 때 데이터를 찾을 수 없는 경우 null 값을 반환하기때문에 생기는 에러입니다. 그래서 return 하기전에 반환값이 null이면 에러를 throw하는 코드를 작성하여 해당 에러를 없앨 수 있습니다.

해결방안:
![스크린샷 2022-06-22 오후 3 49 46](https://user-images.githubusercontent.com/89785501/174962619-e0d32be3-f351-4a36-ad6f-89905ca0b041.png)

**Comment by 89yunik** [comment]
네 좋습니다. 코딩 컨벤션을 위해 guestbook에도 같은 방식으로 falsy 값 처리 기능 추가하겠습니다.

**Comment by MCprotein** [comment]
넵 감사합니다
