### ISSUE TITLE
ObjectId 타입 에러 검토 요청 - 익님

### ISSUE THREAD

**Issue by MCprotein** [elice-promotion-site-team/elice-promotion-site-backend#6]
![스크린샷 2022-06-19 오전 3 00 45](https://user-images.githubusercontent.com/89785501/174451004-1caf9d11-6e92-4f58-b69a-5c8c371b9621.png)

model 내부 각 메서드 return 값에 as any가 없으면 `Type 'ObjectId' is not assignable to type 'string'.` 에러가 발생합니다. <br></br>
![스크린샷 2022-06-19 오전 3 02 14](https://user-images.githubusercontent.com/89785501/174451029-a5ac27a8-0db3-4809-b52c-21580114e7dd.png) <br></br>

@89yunik dev에 있는 익님 model을 그대로 복붙 해봐도 똑같은 에러가 나더라구요
익님은 저런 에러 안나셨나요?

**Comment by 89yunik** [comment]
저도 같은 에러 발생해서 해당 부분 주석 처리해 놓았습니다. as any는 근본적인 해결책은 아닌 거 같아서 해결책 찾게 되면 공유하겠습니다.

**Comment by MCprotein** [comment]
네 저도 계속 찾아보겠습니다 감사합니다
