### ISSUE TITLE
Pull requests 문제 검토 요청 - 익님

### ISSUE THREAD

**Issue by MCprotein** [elice-promotion-site-team/elice-promotion-site-backend#7]
채팅 기본 기능 구현을 완료하여 dev에 Pull requests하려고 하는데, 제 코드가 기존의 코드를 모두 덮어씌우도록 코드가 자동완성 됩니다.
예를들어 package.json에서 익님이 설치해두셨던 모듈을 삭제하고 제가 설치한 모듈만 존재하도록 되더라구요.

Gitlab에서는 비교해서 기존의 코드 + 새 코드 합치는기능이 있었는데 github에는 그런기능이 없나요?
이 경우 어떻게 하면 좋을지 조언 부탁드립니다.
![스크린샷 2022-06-19 오전 3 07 04](https://user-images.githubusercontent.com/89785501/174451180-3185b73e-86ce-48f6-ad5a-a9bdd5c9dc0c.png)
![스크린샷 2022-06-19 오전 3 07 11](https://user-images.githubusercontent.com/89785501/174451181-283587c7-089e-43b6-8d7a-4b7d481a3647.png)

**Comment by 89yunik** [comment]
github도 gitlab과 동일하게 merge conflict 발생하는 걸로 알고 있습니다. 왜 발생하지 않는지는 잘 모르겠네요. 양이 많지 않다면 수동으로 윤수님 코드에서 덮어쓰는 부분에 제 코드 추가하셔야 할 것 같습니다.

**Comment by MCprotein** [comment]
좀더 찾아보고 안되면 말씀하신 대로 복붙 해서 올리겠습니다 감사합니다
